name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # v0.0.1 형식의 태그가 붙으면 워크플로우 실행

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'      # NuGet.Config 파일 생성
    - name: Create NuGet.Config
      run: |
        cat > nuget.config << EOF
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
            <add key="github" value="https://nuget.pkg.github.com/StudioBside/index.json" />
          </packageSources>
          <packageSourceCredentials>
            <github>
              <add key="Username" value="${{ github.actor }}" />
              <add key="ClearTextPassword" value="${{ secrets.STUDIOBSIDE_PAT }}" />
            </github>
          </packageSourceCredentials>
        </configuration>
        EOF
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Update package version in csproj
      run: |
        VERSION=${{ steps.get_version.outputs.VERSION }}
        sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|g" GetP4Revisions/GetP4Revisions.csproj
    
    - name: Build
      run: dotnet build GetP4Revisions/GetP4Revisions.csproj --configuration Release --no-restore
      
    - name: Create NuGet package
      run: dotnet pack GetP4Revisions/GetP4Revisions.csproj --configuration Release --no-build
    
    - name: Setup NuGet credentials for GitHub Packages
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish NuGet package to GitHub Packages
      run: dotnet nuget push GetP4Revisions/nupkg/GetP4Revisions.*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
